spring.application.name=raizes-api

spring.datasource.url=jdbc:h2:mem:raizesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}

app.admin-inicial.nome=${ADMIN_INICIAL_NOME}
app.admin-inicial.email=${ADMIN_INICIAL_EMAIL}
app.admin-inicial.senha=${ADMIN_INICIAL_SENHA}

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.path=/swagger-ui.html