spring.application.name=raizes-api

spring.datasource.url=jdbc:h2:mem:
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

app.security.jwt.secret=chave-super-secreta-do-projeto-raizes-api-com-no-minimo-32-caracteres
app.security.jwt.expiration-minutes=60